[build-system]
requires = ['setuptools>=78.1.1', 'wheel']
build-backend = "setuptools.build_meta"

[tool.djlint]
profile="django"
ignore="H006"

[tool.ruff]
target-version = "py311"
line-length = 119

[tool.ruff.format]

[tool.ruff.lint]
preview = true

select = ["ALL"]
# A003 is triggered only sometimes!
ignore = [
  "ARG001",
  "ARG002",
  "ARG003",
  "ANN001",
  "ANN002",
  "ANN003",
  "COM819",
  "EM101",
  "D100",  # missing docstring in public module
  "D101",  # missing docstring in public class   - 🤔 mixed feelings
  "D103",  # missing docstring in public function (?)
  "D104",  # missing docstring in public package
  "D105",  # missing docstring in magic method
  "D106",  # Missing docstring in public nested class
  "D200",
  "D212","D203",
  "CPY001",
  "G004",  # logging statement uses f-string
  "DOC201",  # "return" is not documented in docstring (too invasive)
  "ANN201",  # missing return type annotation for private function
  "ANN202",  # missing return type annotation for public function
  "ANN204",  # missing return type annotation for special method
  "ANN401",  # Any disallowed   - 🤔
  "TD",
  "FIX",
  "TID252",
  "PLC0414",
  "FBT001",
  "FBT002",
  "FBT003",
  "RUF012",
  "PLR2004",
  "T201",
  "INP001",
  ]

fixable = ["ALL"]
unfixable = []
extend-select = [
  "I",  # isort
]

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = [
  "S101",
  "PLR0913",  # Too many arguments in function definition
  "PLR0917",  # Too many positional arguments
]
