[metadata]
name = wjs-themes
version = 1.0.6.dev6
description = WJS themes collection
author = Matteo Gamboz
author_email = gamboz@medialab.sissa.it
license = AGPL-3.0-or-later
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
url = https://gitlab.sissamedialab.it/wjs/wjs-themes
platforms = any

# https://pypi.org/classifiers/
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Intended Audience :: Developers
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content


[options]
packages = find_namespace:
include_package_data = True
install_requires =
    django-bootstrap5

[options.packages.find]
include = wjs*

[options.package_data]
* =
    *.html
    *.css
    *.woff
    *.woff2
    *.js
    *.scss
    *.po
    *.mo
    *.png
